# Generated by Django 3.2.8 on 2021-10-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='to_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='subject',
        ),
    ]
