# Generated by Django 3.2.8 on 2021-10-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_auto_20211027_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='emailmodel',
            options={'ordering': ('created',)},
        ),
    ]
